name: flutter_redux_hookers
description:
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  redux: ">=5.0.0 <6.0.0"
  flutter_hooks: ">=0.14.1 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
